// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package store

import (
	"context"
	"database/sql"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (id, name, kind, provider_id, secret_source, secret_locator, description)
VALUES (lower(hex(randomblob(16))), ?, ?, ?, ?, ?, ?)
RETURNING id, name, kind, provider_id, secret_source, secret_locator, description, created_at, updated_at
`

type CreateCredentialParams struct {
	Name          string         `json:"name"`
	Kind          string         `json:"kind"`
	ProviderID    sql.NullString `json:"provider_id"`
	SecretSource  string         `json:"secret_source"`
	SecretLocator string         `json:"secret_locator"`
	Description   sql.NullString `json:"description"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredential,
		arg.Name,
		arg.Kind,
		arg.ProviderID,
		arg.SecretSource,
		arg.SecretLocator,
		arg.Description,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.ProviderID,
		&i.SecretSource,
		&i.SecretLocator,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE name = ?
`

func (q *Queries) DeleteCredential(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, name)
	return err
}

const getCredentialByName = `-- name: GetCredentialByName :one
SELECT id, name, kind, provider_id, secret_source, secret_locator, description, created_at, updated_at
FROM credentials
WHERE name = ?
`

func (q *Queries) GetCredentialByName(ctx context.Context, name string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByName, name)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.ProviderID,
		&i.SecretSource,
		&i.SecretLocator,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, name, kind, provider_id, secret_source, secret_locator, description, created_at, updated_at
FROM credentials
ORDER BY name ASC
`

func (q *Queries) ListCredentials(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.ProviderID,
			&i.SecretSource,
			&i.SecretLocator,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
