// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (
    project_id, task_id, run_id, name, kind, content, managed_path,
    external_url, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, task_id, run_id, name, kind, content, managed_path, external_url, metadata, created_at, updated_at
`

type CreateArtifactParams struct {
	ProjectID   string      `json:"project_id"`
	TaskID      pgtype.Text `json:"task_id"`
	RunID       pgtype.UUID `json:"run_id"`
	Name        string      `json:"name"`
	Kind        string      `json:"kind"`
	Content     pgtype.Text `json:"content"`
	ManagedPath pgtype.Text `json:"managed_path"`
	ExternalUrl pgtype.Text `json:"external_url"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ProjectID,
		arg.TaskID,
		arg.RunID,
		arg.Name,
		arg.Kind,
		arg.Content,
		arg.ManagedPath,
		arg.ExternalUrl,
		arg.Metadata,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.Name,
		&i.Kind,
		&i.Content,
		&i.ManagedPath,
		&i.ExternalUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJournal = `-- name: CreateJournal :one
INSERT INTO journals (workspace_id, project_id, title, content, journal_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, project_id, title, content, journal_date, created_at, updated_at
`

type CreateJournalParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ProjectID   string      `json:"project_id"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	JournalDate pgtype.Date `json:"journal_date"`
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, createJournal,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.JournalDate,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.JournalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createKnowledgeWorkspace = `-- name: CreateKnowledgeWorkspace :one

INSERT INTO knowledge_workspaces (project_id, name, layout, status, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, layout, status, metadata, created_at, updated_at
`

type CreateKnowledgeWorkspaceParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	Layout    string `json:"layout"`
	Status    string `json:"status"`
	Metadata  []byte `json:"metadata"`
}

// Knowledge Center CRUD: workspaces, journals and managed artifacts.
func (q *Queries) CreateKnowledgeWorkspace(ctx context.Context, arg CreateKnowledgeWorkspaceParams) (KnowledgeWorkspace, error) {
	row := q.db.QueryRow(ctx, createKnowledgeWorkspace,
		arg.ProjectID,
		arg.Name,
		arg.Layout,
		arg.Status,
		arg.Metadata,
	)
	var i KnowledgeWorkspace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Layout,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, project_id, task_id, run_id, name, kind, content, managed_path, external_url, metadata, created_at, updated_at FROM artifacts WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.Name,
		&i.Kind,
		&i.Content,
		&i.ManagedPath,
		&i.ExternalUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournal = `-- name: GetJournal :one
SELECT id, workspace_id, project_id, title, content, journal_date, created_at, updated_at FROM journals WHERE id = $1
`

func (q *Queries) GetJournal(ctx context.Context, id pgtype.UUID) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournal, id)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.JournalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKnowledgeWorkspace = `-- name: GetKnowledgeWorkspace :one
SELECT id, project_id, name, layout, status, metadata, created_at, updated_at FROM knowledge_workspaces WHERE id = $1
`

func (q *Queries) GetKnowledgeWorkspace(ctx context.Context, id pgtype.UUID) (KnowledgeWorkspace, error) {
	row := q.db.QueryRow(ctx, getKnowledgeWorkspace, id)
	var i KnowledgeWorkspace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Layout,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactsByProject = `-- name: ListArtifactsByProject :many
SELECT id, project_id, task_id, run_id, name, kind, content, managed_path, external_url, metadata, created_at, updated_at FROM artifacts
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListArtifactsByProject(ctx context.Context, projectID string) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.RunID,
			&i.Name,
			&i.Kind,
			&i.Content,
			&i.ManagedPath,
			&i.ExternalUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalsByProject = `-- name: ListJournalsByProject :many
SELECT id, workspace_id, project_id, title, content, journal_date, created_at, updated_at FROM journals
WHERE project_id = $1
ORDER BY journal_date DESC, created_at DESC
`

func (q *Queries) ListJournalsByProject(ctx context.Context, projectID string) ([]Journal, error) {
	rows, err := q.db.Query(ctx, listJournalsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.JournalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeWorkspaces = `-- name: ListKnowledgeWorkspaces :many
SELECT id, project_id, name, layout, status, metadata, created_at, updated_at FROM knowledge_workspaces
WHERE status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListKnowledgeWorkspaces(ctx context.Context) ([]KnowledgeWorkspace, error) {
	rows, err := q.db.Query(ctx, listKnowledgeWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeWorkspace{}
	for rows.Next() {
		var i KnowledgeWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Layout,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkillDefinition = `-- name: UpdateSkillDefinition :one
UPDATE skills
SET prompt_template = $2, lifecycle = $3, version = $4
WHERE id = $1
RETURNING id, slug, name, description, category, risk_level, inputs, outputs, steps, compatible_agents, compatible_runtimes, source, source_id, source_ref, version, status, created_at, updated_at, prompt_template, lifecycle
`

type UpdateSkillDefinitionParams struct {
	ID             string      `json:"id"`
	PromptTemplate pgtype.Text `json:"prompt_template"`
	Lifecycle      string      `json:"lifecycle"`
	Version        pgtype.Text `json:"version"`
}

func (q *Queries) UpdateSkillDefinition(ctx context.Context, arg UpdateSkillDefinitionParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkillDefinition,
		arg.ID,
		arg.PromptTemplate,
		arg.Lifecycle,
		arg.Version,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.RiskLevel,
		&i.Inputs,
		&i.Outputs,
		&i.Steps,
		&i.CompatibleAgents,
		&i.CompatibleRuntimes,
		&i.Source,
		&i.SourceID,
		&i.SourceRef,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptTemplate,
		&i.Lifecycle,
	)
	return i, err
}
