// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package store

import (
	"context"
	"database/sql"
)

const countUnreadForAgent = `-- name: CountUnreadForAgent :one
SELECT COUNT(*) FROM agent_messages
WHERE to_agent_id = ? AND read_at IS NULL
`

func (q *Queries) CountUnreadForAgent(ctx context.Context, toAgentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadForAgent, toAgentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentMessage = `-- name: CreateAgentMessage :one
INSERT INTO agent_messages (id, project_id, from_agent_id, to_agent_id, run_id, subject, body)
VALUES (lower(hex(randomblob(16))), ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, from_agent_id, to_agent_id, run_id, subject, body, read_at, created_at
`

type CreateAgentMessageParams struct {
	ProjectID   sql.NullString `json:"project_id"`
	FromAgentID sql.NullString `json:"from_agent_id"`
	ToAgentID   string         `json:"to_agent_id"`
	RunID       sql.NullString `json:"run_id"`
	Subject     sql.NullString `json:"subject"`
	Body        string         `json:"body"`
}

func (q *Queries) CreateAgentMessage(ctx context.Context, arg CreateAgentMessageParams) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, createAgentMessage,
		arg.ProjectID,
		arg.FromAgentID,
		arg.ToAgentID,
		arg.RunID,
		arg.Subject,
		arg.Body,
	)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromAgentID,
		&i.ToAgentID,
		&i.RunID,
		&i.Subject,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInboxForAgent = `-- name: ListInboxForAgent :many
SELECT id, project_id, from_agent_id, to_agent_id, run_id, subject, body, read_at, created_at
FROM agent_messages
WHERE to_agent_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListInboxForAgentParams struct {
	ToAgentID string `json:"to_agent_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListInboxForAgent(ctx context.Context, arg ListInboxForAgentParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listInboxForAgent, arg.ToAgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromAgentID,
			&i.ToAgentID,
			&i.RunID,
			&i.Subject,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadInboxForAgent = `-- name: ListUnreadInboxForAgent :many
SELECT id, project_id, from_agent_id, to_agent_id, run_id, subject, body, read_at, created_at
FROM agent_messages
WHERE to_agent_id = ? AND read_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListUnreadInboxForAgent(ctx context.Context, toAgentID string) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadInboxForAgent, toAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromAgentID,
			&i.ToAgentID,
			&i.RunID,
			&i.Subject,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentMessageRead = `-- name: MarkAgentMessageRead :one
UPDATE agent_messages
SET read_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, project_id, from_agent_id, to_agent_id, run_id, subject, body, read_at, created_at
`

func (q *Queries) MarkAgentMessageRead(ctx context.Context, id string) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, markAgentMessageRead, id)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromAgentID,
		&i.ToAgentID,
		&i.RunID,
		&i.Subject,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
