// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID              string         `json:"id"`
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Role            sql.NullString `json:"role"`
	Description     sql.NullString `json:"description"`
	RuntimeID       sql.NullString `json:"runtime_id"`
	RuntimeConfig   string         `json:"runtime_config"`
	SystemPrompt    sql.NullString `json:"system_prompt"`
	AllowedTools    string         `json:"allowed_tools"`
	AllowedProjects string         `json:"allowed_projects"`
	RiskLevel       string         `json:"risk_level"`
	IsLead          int64          `json:"is_lead"`
	IsMeta          int64          `json:"is_meta"`
	Status          string         `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type AgentMessage struct {
	ID          string         `json:"id"`
	ProjectID   sql.NullString `json:"project_id"`
	FromAgentID sql.NullString `json:"from_agent_id"`
	ToAgentID   string         `json:"to_agent_id"`
	RunID       sql.NullString `json:"run_id"`
	Subject     sql.NullString `json:"subject"`
	Body        string         `json:"body"`
	ReadAt      sql.NullTime   `json:"read_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type AgentRuntime struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Kind         string         `json:"kind"`
	Status       string         `json:"status"`
	BinaryPath   sql.NullString `json:"binary_path"`
	Version      sql.NullString `json:"version"`
	EndpointUrl  sql.NullString `json:"endpoint_url"`
	RiskLevel    string         `json:"risk_level"`
	RequiresAuth int64          `json:"requires_auth"`
	Capabilities string         `json:"capabilities"`
	ConfigSchema string         `json:"config_schema"`
	DetectedAt   sql.NullTime   `json:"detected_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Artifact struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	TaskID      sql.NullString `json:"task_id"`
	RunID       sql.NullString `json:"run_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	Content     sql.NullString `json:"content"`
	ManagedPath sql.NullString `json:"managed_path"`
	ExternalUrl sql.NullString `json:"external_url"`
	Metadata    string         `json:"metadata"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type AuditLog struct {
	ID         string    `json:"id"`
	Action     string    `json:"action"`
	Actor      string    `json:"actor"`
	TargetType string    `json:"target_type"`
	TargetID   string    `json:"target_id"`
	Details    string    `json:"details"`
	IpAddress  string    `json:"ip_address"`
	CreatedAt  time.Time `json:"created_at"`
}

type CliTool struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Command        string         `json:"command"`
	Kind           string         `json:"kind"`
	DetectedPath   sql.NullString `json:"detected_path"`
	Version        sql.NullString `json:"version"`
	RuntimeID      sql.NullString `json:"runtime_id"`
	Status         string         `json:"status"`
	RiskLevel      string         `json:"risk_level"`
	RequiresAuth   int64          `json:"requires_auth"`
	Capabilities   string         `json:"capabilities"`
	LastDetectedAt sql.NullTime   `json:"last_detected_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Credential struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Kind          string         `json:"kind"`
	ProviderID    sql.NullString `json:"provider_id"`
	SecretSource  string         `json:"secret_source"`
	SecretLocator string         `json:"secret_locator"`
	Description   sql.NullString `json:"description"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Domain struct {
	ID          string         `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Metadata    string         `json:"metadata"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Goal struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Metadata    string         `json:"metadata"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Journal struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	ProjectID   string    `json:"project_id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	JournalDate time.Time `json:"journal_date"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type KnowledgeWorkspace struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	Name      string    `json:"name"`
	Layout    string    `json:"layout"`
	Status    string    `json:"status"`
	Metadata  string    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type McpConnection struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Transport    string         `json:"transport"`
	Command      sql.NullString `json:"command"`
	Args         string         `json:"args"`
	Env          string         `json:"env"`
	Url          sql.NullString `json:"url"`
	Status       string         `json:"status"`
	HealthScore  int64          `json:"health_score"`
	LastSyncAt   sql.NullTime   `json:"last_sync_at"`
	SourceUrl    sql.NullString `json:"source_url"`
	ProjectScope string         `json:"project_scope"`
	Permissions  string         `json:"permissions"`
	RiskLevel    string         `json:"risk_level"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type MemoryItem struct {
	ID        int64          `json:"id"`
	Type      string         `json:"type"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	TopicKey  sql.NullString `json:"topic_key"`
	ProjectID sql.NullString `json:"project_id"`
	AgentID   sql.NullString `json:"agent_id"`
	Scope     string         `json:"scope"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type MemoryItemsFt struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	TopicKey string `json:"topic_key"`
}

type Model struct {
	ID               string          `json:"id"`
	ProviderID       string          `json:"provider_id"`
	Name             string          `json:"name"`
	Tier             int64           `json:"tier"`
	ContextWindow    int64           `json:"context_window"`
	SupportsTools    int64           `json:"supports_tools"`
	SupportsVision   int64           `json:"supports_vision"`
	SupportsCode     int64           `json:"supports_code"`
	InputPricePer1m  sql.NullFloat64 `json:"input_price_per_1m"`
	OutputPricePer1m sql.NullFloat64 `json:"output_price_per_1m"`
	Status           string          `json:"status"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type NovacoreConversation struct {
	ID                string         `json:"id"`
	UserID            sql.NullString `json:"user_id"`
	StartedAt         time.Time      `json:"started_at"`
	EndedAt           sql.NullTime   `json:"ended_at"`
	MessageCount      int64          `json:"message_count"`
	TotalInputTokens  int64          `json:"total_input_tokens"`
	TotalOutputTokens int64          `json:"total_output_tokens"`
	TotalCostUsd      float64        `json:"total_cost_usd"`
}

type NovacoreMessage struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	Role           string         `json:"role"`
	Content        sql.NullString `json:"content"`
	ToolCalls      sql.NullString `json:"tool_calls"`
	ToolResult     sql.NullString `json:"tool_result"`
	TokensIn       int64          `json:"tokens_in"`
	TokensOut      int64          `json:"tokens_out"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Project struct {
	ID               string          `json:"id"`
	Slug             string          `json:"slug"`
	Name             string          `json:"name"`
	Description      sql.NullString  `json:"description"`
	Status           string          `json:"status"`
	OwnerAgentID     sql.NullString  `json:"owner_agent_id"`
	MonthlyBudgetUsd sql.NullFloat64 `json:"monthly_budget_usd"`
	Metadata         string          `json:"metadata"`
	DomainID         sql.NullString  `json:"domain_id"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type Provider struct {
	ID               string          `json:"id"`
	Name             string          `json:"name"`
	Kind             string          `json:"kind"`
	EnvKey           string          `json:"env_key"`
	DocsUrl          sql.NullString  `json:"docs_url"`
	Status           string          `json:"status"`
	MonthlyBudgetUsd sql.NullFloat64 `json:"monthly_budget_usd"`
	MonthlySpendUsd  float64         `json:"monthly_spend_usd"`
	LastCheckAt      sql.NullTime    `json:"last_check_at"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type Repository struct {
	ID            string         `json:"id"`
	ProjectID     string         `json:"project_id"`
	Kind          string         `json:"kind"`
	Name          string         `json:"name"`
	RemoteUrl     sql.NullString `json:"remote_url"`
	CredentialRef sql.NullString `json:"credential_ref"`
	DefaultBranch string         `json:"default_branch"`
	Metadata      string         `json:"metadata"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Run struct {
	ID                 string         `json:"id"`
	ProjectID          string         `json:"project_id"`
	TaskID             string         `json:"task_id"`
	AgentID            string         `json:"agent_id"`
	SkillID            sql.NullString `json:"skill_id"`
	RuntimeAdapterID   string         `json:"runtime_adapter_id"`
	RepositoryID       sql.NullString `json:"repository_id"`
	Prompt             string         `json:"prompt"`
	RequestedNetwork   int64          `json:"requested_network"`
	NetworkEnabled     int64          `json:"network_enabled"`
	HostSessionEnabled int64          `json:"host_session_enabled"`
	ExecutionMode      string         `json:"execution_mode"`
	Status             string         `json:"status"`
	BranchName         sql.NullString `json:"branch_name"`
	ResultSummary      sql.NullString `json:"result_summary"`
	ErrorMessage       sql.NullString `json:"error_message"`
	EstimatedCostUsd   float64        `json:"estimated_cost_usd"`
	Metadata           string         `json:"metadata"`
	StartedAt          sql.NullTime   `json:"started_at"`
	CompletedAt        sql.NullTime   `json:"completed_at"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type RunApproval struct {
	ID        string         `json:"id"`
	RunID     string         `json:"run_id"`
	Kind      string         `json:"kind"`
	Decision  string         `json:"decision"`
	Reason    sql.NullString `json:"reason"`
	DecidedAt time.Time      `json:"decided_at"`
}

type RunLog struct {
	ID        int64     `json:"id"`
	RunID     string    `json:"run_id"`
	Stream    string    `json:"stream"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}

type Skill struct {
	ID                 string         `json:"id"`
	Slug               string         `json:"slug"`
	Name               string         `json:"name"`
	Description        sql.NullString `json:"description"`
	Category           sql.NullString `json:"category"`
	RiskLevel          string         `json:"risk_level"`
	Inputs             string         `json:"inputs"`
	Outputs            string         `json:"outputs"`
	Steps              sql.NullString `json:"steps"`
	CompatibleAgents   string         `json:"compatible_agents"`
	CompatibleRuntimes string         `json:"compatible_runtimes"`
	Source             string         `json:"source"`
	SourceID           sql.NullString `json:"source_id"`
	SourceRef          sql.NullString `json:"source_ref"`
	Version            sql.NullString `json:"version"`
	Status             string         `json:"status"`
	PromptTemplate     sql.NullString `json:"prompt_template"`
	Lifecycle          string         `json:"lifecycle"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type SkillSource struct {
	ID           string       `json:"id"`
	Name         string       `json:"name"`
	Url          string       `json:"url"`
	TrustLevel   string       `json:"trust_level"`
	LastSyncedAt sql.NullTime `json:"last_synced_at"`
	Enabled      int64        `json:"enabled"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type SystemLog struct {
	ID        string    `json:"id"`
	Level     string    `json:"level"`
	Source    string    `json:"source"`
	Message   string    `json:"message"`
	Context   string    `json:"context"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	GoalID          sql.NullString `json:"goal_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	AssignedAgentID sql.NullString `json:"assigned_agent_id"`
	Status          string         `json:"status"`
	BoardPosition   int64          `json:"board_position"`
	Metadata        string         `json:"metadata"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type UsageEvent struct {
	ID               string         `json:"id"`
	RunID            sql.NullString `json:"run_id"`
	ProviderID       sql.NullString `json:"provider_id"`
	ModelID          sql.NullString `json:"model_id"`
	ProjectID        sql.NullString `json:"project_id"`
	AgentID          sql.NullString `json:"agent_id"`
	SkillID          sql.NullString `json:"skill_id"`
	InputTokens      int64          `json:"input_tokens"`
	OutputTokens     int64          `json:"output_tokens"`
	CachedTokens     int64          `json:"cached_tokens"`
	RequestCount     int64          `json:"request_count"`
	EstimatedCostUsd float64        `json:"estimated_cost_usd"`
	CreatedAt        time.Time      `json:"created_at"`
}
