// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID              string             `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	Role            pgtype.Text        `json:"role"`
	Description     pgtype.Text        `json:"description"`
	RuntimeID       pgtype.Text        `json:"runtime_id"`
	RuntimeConfig   []byte             `json:"runtime_config"`
	SystemPrompt    pgtype.Text        `json:"system_prompt"`
	AllowedTools    []byte             `json:"allowed_tools"`
	AllowedProjects []byte             `json:"allowed_projects"`
	RiskLevel       string             `json:"risk_level"`
	IsLead          bool               `json:"is_lead"`
	IsMeta          bool               `json:"is_meta"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AgentRuntime struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Kind         string             `json:"kind"`
	Status       string             `json:"status"`
	BinaryPath   pgtype.Text        `json:"binary_path"`
	Version      pgtype.Text        `json:"version"`
	EndpointUrl  pgtype.Text        `json:"endpoint_url"`
	RiskLevel    string             `json:"risk_level"`
	RequiresAuth bool               `json:"requires_auth"`
	Capabilities []byte             `json:"capabilities"`
	ConfigSchema []byte             `json:"config_schema"`
	DetectedAt   pgtype.Timestamptz `json:"detected_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Artifact struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   string             `json:"project_id"`
	TaskID      pgtype.Text        `json:"task_id"`
	RunID       pgtype.UUID        `json:"run_id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	Content     pgtype.Text        `json:"content"`
	ManagedPath pgtype.Text        `json:"managed_path"`
	ExternalUrl pgtype.Text        `json:"external_url"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	Actor      string             `json:"actor"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Details    []byte             `json:"details"`
	IpAddress  string             `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CliTool struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	Command        string             `json:"command"`
	Kind           string             `json:"kind"`
	DetectedPath   pgtype.Text        `json:"detected_path"`
	Version        pgtype.Text        `json:"version"`
	RuntimeID      pgtype.Text        `json:"runtime_id"`
	Status         string             `json:"status"`
	RiskLevel      string             `json:"risk_level"`
	RequiresAuth   bool               `json:"requires_auth"`
	Capabilities   []byte             `json:"capabilities"`
	LastDetectedAt pgtype.Timestamptz `json:"last_detected_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Domain struct {
	ID          string             `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Execution struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.Text        `json:"project_id"`
	AgentID          pgtype.Text        `json:"agent_id"`
	SkillID          pgtype.Text        `json:"skill_id"`
	ModelID          pgtype.Text        `json:"model_id"`
	RuntimeID        pgtype.Text        `json:"runtime_id"`
	UserRequest      pgtype.Text        `json:"user_request"`
	ResultSummary    pgtype.Text        `json:"result_summary"`
	Status           string             `json:"status"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	InputTokens      int32              `json:"input_tokens"`
	OutputTokens     int32              `json:"output_tokens"`
	EstimatedCostUsd pgtype.Numeric     `json:"estimated_cost_usd"`
	LatencyMs        int32              `json:"latency_ms"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type Goal struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Journal struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ProjectID   string             `json:"project_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	JournalDate pgtype.Date        `json:"journal_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type KnowledgeWorkspace struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID string             `json:"project_id"`
	Name      string             `json:"name"`
	Layout    string             `json:"layout"`
	Status    string             `json:"status"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type McpConnection struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Transport    string             `json:"transport"`
	Command      pgtype.Text        `json:"command"`
	Args         []byte             `json:"args"`
	Env          []byte             `json:"env"`
	Url          pgtype.Text        `json:"url"`
	Status       string             `json:"status"`
	HealthScore  int16              `json:"health_score"`
	LastSyncAt   pgtype.Timestamptz `json:"last_sync_at"`
	SourceUrl    pgtype.Text        `json:"source_url"`
	ProjectScope []byte             `json:"project_scope"`
	Permissions  []byte             `json:"permissions"`
	RiskLevel    string             `json:"risk_level"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Model struct {
	ID               string             `json:"id"`
	ProviderID       string             `json:"provider_id"`
	Name             string             `json:"name"`
	Tier             int16              `json:"tier"`
	ContextWindow    int32              `json:"context_window"`
	SupportsTools    bool               `json:"supports_tools"`
	SupportsVision   bool               `json:"supports_vision"`
	SupportsCode     bool               `json:"supports_code"`
	InputPricePer1m  pgtype.Numeric     `json:"input_price_per_1m"`
	OutputPricePer1m pgtype.Numeric     `json:"output_price_per_1m"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type NovacoreConversation struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.Text        `json:"user_id"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
	MessageCount      int32              `json:"message_count"`
	TotalInputTokens  int32              `json:"total_input_tokens"`
	TotalOutputTokens int32              `json:"total_output_tokens"`
	TotalCostUsd      pgtype.Numeric     `json:"total_cost_usd"`
}

type NovacoreMessage struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        pgtype.Text        `json:"content"`
	ToolCalls      []byte             `json:"tool_calls"`
	ToolResult     []byte             `json:"tool_result"`
	TokensIn       int32              `json:"tokens_in"`
	TokensOut      int32              `json:"tokens_out"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID               string             `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	Status           string             `json:"status"`
	OwnerAgentID     pgtype.Text        `json:"owner_agent_id"`
	MonthlyBudgetUsd pgtype.Numeric     `json:"monthly_budget_usd"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DomainID         pgtype.Text        `json:"domain_id"`
}

type Provider struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	Kind             string             `json:"kind"`
	EnvKey           string             `json:"env_key"`
	DocsUrl          pgtype.Text        `json:"docs_url"`
	Status           string             `json:"status"`
	MonthlyBudgetUsd pgtype.Numeric     `json:"monthly_budget_usd"`
	MonthlySpendUsd  pgtype.Numeric     `json:"monthly_spend_usd"`
	LastCheckAt      pgtype.Timestamptz `json:"last_check_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Repository struct {
	ID            string             `json:"id"`
	ProjectID     string             `json:"project_id"`
	Kind          string             `json:"kind"`
	Name          string             `json:"name"`
	RemoteUrl     pgtype.Text        `json:"remote_url"`
	CredentialRef pgtype.Text        `json:"credential_ref"`
	DefaultBranch string             `json:"default_branch"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Run struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        string             `json:"project_id"`
	TaskID           string             `json:"task_id"`
	AgentID          string             `json:"agent_id"`
	SkillID          pgtype.Text        `json:"skill_id"`
	RuntimeAdapterID string             `json:"runtime_adapter_id"`
	RepositoryID     pgtype.Text        `json:"repository_id"`
	Prompt           string             `json:"prompt"`
	RequestedNetwork bool               `json:"requested_network"`
	NetworkEnabled   bool               `json:"network_enabled"`
	Status           string             `json:"status"`
	BranchName       pgtype.Text        `json:"branch_name"`
	ResultSummary    pgtype.Text        `json:"result_summary"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	EstimatedCostUsd pgtype.Numeric     `json:"estimated_cost_usd"`
	Metadata         []byte             `json:"metadata"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RunApproval struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Kind      string             `json:"kind"`
	Decision  string             `json:"decision"`
	Reason    pgtype.Text        `json:"reason"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
}

type RunLog struct {
	ID        int64              `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Stream    string             `json:"stream"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Skill struct {
	ID                 string             `json:"id"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Category           pgtype.Text        `json:"category"`
	RiskLevel          string             `json:"risk_level"`
	Inputs             []byte             `json:"inputs"`
	Outputs            []byte             `json:"outputs"`
	Steps              pgtype.Text        `json:"steps"`
	CompatibleAgents   []byte             `json:"compatible_agents"`
	CompatibleRuntimes []byte             `json:"compatible_runtimes"`
	Source             string             `json:"source"`
	SourceID           pgtype.Text        `json:"source_id"`
	SourceRef          pgtype.Text        `json:"source_ref"`
	Version            pgtype.Text        `json:"version"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	PromptTemplate     pgtype.Text        `json:"prompt_template"`
	Lifecycle          string             `json:"lifecycle"`
}

type SkillSource struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Url          string             `json:"url"`
	TrustLevel   string             `json:"trust_level"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SystemLog struct {
	ID        pgtype.UUID        `json:"id"`
	Level     string             `json:"level"`
	Source    string             `json:"source"`
	Message   string             `json:"message"`
	Context   []byte             `json:"context"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID              string             `json:"id"`
	ProjectID       string             `json:"project_id"`
	GoalID          pgtype.Text        `json:"goal_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	AssignedAgentID pgtype.Text        `json:"assigned_agent_id"`
	Status          string             `json:"status"`
	BoardPosition   int32              `json:"board_position"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UsageEvent struct {
	ID               pgtype.UUID        `json:"id"`
	RunID            pgtype.UUID        `json:"run_id"`
	ProviderID       pgtype.Text        `json:"provider_id"`
	ModelID          pgtype.Text        `json:"model_id"`
	ProjectID        pgtype.Text        `json:"project_id"`
	AgentID          pgtype.Text        `json:"agent_id"`
	SkillID          pgtype.Text        `json:"skill_id"`
	InputTokens      int32              `json:"input_tokens"`
	OutputTokens     int32              `json:"output_tokens"`
	CachedTokens     int32              `json:"cached_tokens"`
	RequestCount     int32              `json:"request_count"`
	EstimatedCostUsd pgtype.Numeric     `json:"estimated_cost_usd"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
