// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: novacore.sql

package store

import (
	"context"
	"database/sql"
)

const createNovaConversation = `-- name: CreateNovaConversation :one
INSERT INTO novacore_conversations (id, user_id)
VALUES (lower(hex(randomblob(16))), ?)
RETURNING id, user_id, started_at, ended_at, message_count, total_input_tokens, total_output_tokens, total_cost_usd
`

func (q *Queries) CreateNovaConversation(ctx context.Context, userID sql.NullString) (NovacoreConversation, error) {
	row := q.db.QueryRowContext(ctx, createNovaConversation, userID)
	var i NovacoreConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.MessageCount,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCostUsd,
	)
	return i, err
}

const createNovaMessage = `-- name: CreateNovaMessage :one
INSERT INTO novacore_messages (id, conversation_id, role, content, tool_calls, tool_result, tokens_in, tokens_out)
VALUES (lower(hex(randomblob(16))), ?, ?, ?, ?, ?, ?, ?)
RETURNING id, conversation_id, role, content, tool_calls, tool_result, tokens_in, tokens_out, created_at
`

type CreateNovaMessageParams struct {
	ConversationID string         `json:"conversation_id"`
	Role           string         `json:"role"`
	Content        sql.NullString `json:"content"`
	ToolCalls      sql.NullString `json:"tool_calls"`
	ToolResult     sql.NullString `json:"tool_result"`
	TokensIn       int64          `json:"tokens_in"`
	TokensOut      int64          `json:"tokens_out"`
}

func (q *Queries) CreateNovaMessage(ctx context.Context, arg CreateNovaMessageParams) (NovacoreMessage, error) {
	row := q.db.QueryRowContext(ctx, createNovaMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolResult,
		arg.TokensIn,
		arg.TokensOut,
	)
	var i NovacoreMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolResult,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
	)
	return i, err
}

const getNovaConversation = `-- name: GetNovaConversation :one
SELECT id, user_id, started_at, ended_at, message_count, total_input_tokens, total_output_tokens, total_cost_usd
FROM novacore_conversations
WHERE id = ?
`

func (q *Queries) GetNovaConversation(ctx context.Context, id string) (NovacoreConversation, error) {
	row := q.db.QueryRowContext(ctx, getNovaConversation, id)
	var i NovacoreConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.MessageCount,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCostUsd,
	)
	return i, err
}

const listNovaConversations = `-- name: ListNovaConversations :many
SELECT id, user_id, started_at, ended_at, message_count, total_input_tokens, total_output_tokens, total_cost_usd
FROM novacore_conversations
ORDER BY started_at DESC
`

func (q *Queries) ListNovaConversations(ctx context.Context) ([]NovacoreConversation, error) {
	rows, err := q.db.QueryContext(ctx, listNovaConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NovacoreConversation{}
	for rows.Next() {
		var i NovacoreConversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.MessageCount,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNovaMessagesByConversation = `-- name: ListNovaMessagesByConversation :many
SELECT id, conversation_id, role, content, tool_calls, tool_result, tokens_in, tokens_out, created_at
FROM novacore_messages
WHERE conversation_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListNovaMessagesByConversation(ctx context.Context, conversationID string) ([]NovacoreMessage, error) {
	rows, err := q.db.QueryContext(ctx, listNovaMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NovacoreMessage{}
	for rows.Next() {
		var i NovacoreMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolResult,
			&i.TokensIn,
			&i.TokensOut,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNovaConversationStats = `-- name: UpdateNovaConversationStats :one
UPDATE novacore_conversations
SET message_count = message_count + 1,
    total_input_tokens = total_input_tokens + ?,
    total_output_tokens = total_output_tokens + ?,
    total_cost_usd = total_cost_usd + ?
WHERE id = ?
RETURNING id, user_id, started_at, ended_at, message_count, total_input_tokens, total_output_tokens, total_cost_usd
`

type UpdateNovaConversationStatsParams struct {
	TotalInputTokens  int64   `json:"total_input_tokens"`
	TotalOutputTokens int64   `json:"total_output_tokens"`
	TotalCostUsd      float64 `json:"total_cost_usd"`
	ID                string  `json:"id"`
}

func (q *Queries) UpdateNovaConversationStats(ctx context.Context, arg UpdateNovaConversationStatsParams) (NovacoreConversation, error) {
	row := q.db.QueryRowContext(ctx, updateNovaConversationStats,
		arg.TotalInputTokens,
		arg.TotalOutputTokens,
		arg.TotalCostUsd,
		arg.ID,
	)
	var i NovacoreConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.MessageCount,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCostUsd,
	)
	return i, err
}
