// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	AppendRunLog(ctx context.Context, arg AppendRunLogParams) (RunLog, error)
	CancelRun(ctx context.Context, id string) (Run, error)
	ClaimNextQueuedRun(ctx context.Context) (Run, error)
	ClaimQueuedRunByID(ctx context.Context, id string) (Run, error)
	CompleteRun(ctx context.Context, arg CompleteRunParams) (Run, error)
	CountActiveMCPConnections(ctx context.Context) (int64, error)
	CountAgents(ctx context.Context) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountAvailableRuntimes(ctx context.Context) (int64, error)
	CountDetectedCLITools(ctx context.Context) (int64, error)
	// Queries for basic registries.
	// Solo lectura + counts en Fase 2. CRUD completo viene en Fase 3.
	CountProjects(ctx context.Context) (int64, error)
	CountSkills(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	// Audit log queries para registro de acciones administrativas.
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// Work Board CRUD: domains, projects, goals and tasks.
	CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateJournal(ctx context.Context, arg CreateJournalParams) (Journal, error)
	// Knowledge Center CRUD: workspaces, journals and managed artifacts.
	CreateKnowledgeWorkspace(ctx context.Context, arg CreateKnowledgeWorkspaceParams) (KnowledgeWorkspace, error)
	CreateNovaConversation(ctx context.Context, userID sql.NullString) (NovacoreConversation, error)
	CreateNovaMessage(ctx context.Context, arg CreateNovaMessageParams) (NovacoreMessage, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// Repositories CRUD
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	// Run proposal and approval queries.
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateRunApproval(ctx context.Context, arg CreateRunApprovalParams) (RunApproval, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// Queries para eventos de consumo y uso (usage_events)
	CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error)
	DeleteRepository(ctx context.Context, id string) (Repository, error)
	EnableRunNetwork(ctx context.Context, id string) (Run, error)
	EnsureInboxProject(ctx context.Context) (Project, error)
	FailRun(ctx context.Context, arg FailRunParams) (Run, error)
	GetAgentRuntime(ctx context.Context, id string) (AgentRuntime, error)
	GetArtifact(ctx context.Context, id string) (Artifact, error)
	GetArtifactByRunAndKind(ctx context.Context, arg GetArtifactByRunAndKindParams) (Artifact, error)
	GetDomain(ctx context.Context, id string) (Domain, error)
	GetGoal(ctx context.Context, id string) (Goal, error)
	GetJournal(ctx context.Context, id string) (Journal, error)
	GetKnowledgeWorkspace(ctx context.Context, id string) (KnowledgeWorkspace, error)
	GetNovaConversation(ctx context.Context, id string) (NovacoreConversation, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProvider(ctx context.Context, id string) (Provider, error)
	GetRepository(ctx context.Context, id string) (Repository, error)
	GetRun(ctx context.Context, id string) (Run, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetUsageByRun(ctx context.Context, runID sql.NullString) ([]UsageEvent, error)
	GetUsageOverview(ctx context.Context) ([]GetUsageOverviewRow, error)
	InsertSystemLog(ctx context.Context, arg InsertSystemLogParams) error
	ListAgentRuntimes(ctx context.Context) ([]AgentRuntime, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListArtifactsByProject(ctx context.Context, projectID string) ([]Artifact, error)
	ListArtifactsByRun(ctx context.Context, runID sql.NullString) ([]Artifact, error)
	ListAuditLogs(ctx context.Context, limit int64) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error)
	ListCLITools(ctx context.Context) ([]CliTool, error)
	ListDomains(ctx context.Context) ([]Domain, error)
	ListGoals(ctx context.Context) ([]Goal, error)
	ListGoalsByProject(ctx context.Context, projectID string) ([]Goal, error)
	ListJournalsByProject(ctx context.Context, projectID string) ([]Journal, error)
	ListKnowledgeWorkspaces(ctx context.Context) ([]KnowledgeWorkspace, error)
	ListNovaConversations(ctx context.Context) ([]NovacoreConversation, error)
	ListNovaMessagesByConversation(ctx context.Context, conversationID string) ([]NovacoreMessage, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListRepositories(ctx context.Context) ([]Repository, error)
	ListRepositoriesByProject(ctx context.Context, projectID string) ([]Repository, error)
	ListRunLogs(ctx context.Context, runID string) ([]RunLog, error)
	ListRuns(ctx context.Context) ([]Run, error)
	ListRunsByProject(ctx context.Context, projectID string) ([]Run, error)
	ListSkills(ctx context.Context) ([]Skill, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListTasksByProject(ctx context.Context, projectID string) ([]Task, error)
	// Queries de sistema: healthchecks, logs.
	PingDB(ctx context.Context) (int64, error)
	RecentSystemLogs(ctx context.Context, limit int64) ([]SystemLog, error)
	UpdateAgentRuntimeDetection(ctx context.Context, arg UpdateAgentRuntimeDetectionParams) (AgentRuntime, error)
	UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdateNovaConversationStats(ctx context.Context, arg UpdateNovaConversationStatsParams) (NovacoreConversation, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProviderStatus(ctx context.Context, arg UpdateProviderStatusParams) error
	UpdateRunBranchAndMetadata(ctx context.Context, arg UpdateRunBranchAndMetadataParams) (Run, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error)
	UpdateSkillDefinition(ctx context.Context, arg UpdateSkillDefinitionParams) (Skill, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpsertCLIToolDetection(ctx context.Context, arg UpsertCLIToolDetectionParams) (CliTool, error)
}

var _ Querier = (*Queries)(nil)
