// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountActiveMCPConnections(ctx context.Context) (int32, error)
	CountAgents(ctx context.Context) (int32, error)
	CountAvailableRuntimes(ctx context.Context) (int32, error)
	CountDetectedCLITools(ctx context.Context) (int32, error)
	// Queries para registries básicos.
	// Solo lectura + counts en Fase 2. CRUD completo viene en Fase 3.
	CountProjects(ctx context.Context) (int32, error)
	CountSkills(ctx context.Context) (int32, error)
	GetAgentRuntime(ctx context.Context, id string) (AgentRuntime, error)
	GetProvider(ctx context.Context, id string) (Provider, error)
	InsertSystemLog(ctx context.Context, arg InsertSystemLogParams) error
	ListAgentRuntimes(ctx context.Context) ([]AgentRuntime, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	// Queries de sistema: healthchecks, logs.
	PingDB(ctx context.Context) (int32, error)
	RecentSystemLogs(ctx context.Context, limit int32) ([]SystemLog, error)
	UpdateProviderStatus(ctx context.Context, arg UpdateProviderStatusParams) error
}

var _ Querier = (*Queries)(nil)
