// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registries.sql

package store

import (
	"context"
)

const countActiveMCPConnections = `-- name: CountActiveMCPConnections :one
SELECT COUNT(*)::int AS total FROM mcp_connections WHERE status = 'active'
`

func (q *Queries) CountActiveMCPConnections(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveMCPConnections)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countAgents = `-- name: CountAgents :one
SELECT COUNT(*)::int AS total FROM agents WHERE status = 'active'
`

func (q *Queries) CountAgents(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countAgents)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countAvailableRuntimes = `-- name: CountAvailableRuntimes :one
SELECT COUNT(*)::int AS total FROM agent_runtimes WHERE status = 'available'
`

func (q *Queries) CountAvailableRuntimes(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countAvailableRuntimes)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countDetectedCLITools = `-- name: CountDetectedCLITools :one
SELECT COUNT(*)::int AS total FROM cli_tools WHERE status = 'detected'
`

func (q *Queries) CountDetectedCLITools(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countDetectedCLITools)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countProjects = `-- name: CountProjects :one

SELECT COUNT(*)::int AS total FROM projects WHERE status != 'archived'
`

// Queries para registries básicos.
// Solo lectura + counts en Fase 2. CRUD completo viene en Fase 3.
func (q *Queries) CountProjects(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countSkills = `-- name: CountSkills :one
SELECT COUNT(*)::int AS total FROM skills WHERE status = 'active'
`

func (q *Queries) CountSkills(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countSkills)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getAgentRuntime = `-- name: GetAgentRuntime :one
SELECT id, name, kind, status, binary_path, version, endpoint_url, risk_level, requires_auth, capabilities, config_schema, detected_at, created_at, updated_at FROM agent_runtimes WHERE id = $1
`

func (q *Queries) GetAgentRuntime(ctx context.Context, id string) (AgentRuntime, error) {
	row := q.db.QueryRow(ctx, getAgentRuntime, id)
	var i AgentRuntime
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.BinaryPath,
		&i.Version,
		&i.EndpointUrl,
		&i.RiskLevel,
		&i.RequiresAuth,
		&i.Capabilities,
		&i.ConfigSchema,
		&i.DetectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, kind, env_key, docs_url, status, monthly_budget_usd, monthly_spend_usd, last_check_at, created_at, updated_at FROM providers WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.EnvKey,
		&i.DocsUrl,
		&i.Status,
		&i.MonthlyBudgetUsd,
		&i.MonthlySpendUsd,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentRuntimes = `-- name: ListAgentRuntimes :many
SELECT id, name, kind, status, binary_path, version, endpoint_url, risk_level, requires_auth, capabilities, config_schema, detected_at, created_at, updated_at FROM agent_runtimes ORDER BY id
`

func (q *Queries) ListAgentRuntimes(ctx context.Context) ([]AgentRuntime, error) {
	rows, err := q.db.Query(ctx, listAgentRuntimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRuntime{}
	for rows.Next() {
		var i AgentRuntime
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Status,
			&i.BinaryPath,
			&i.Version,
			&i.EndpointUrl,
			&i.RiskLevel,
			&i.RequiresAuth,
			&i.Capabilities,
			&i.ConfigSchema,
			&i.DetectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, kind, env_key, docs_url, status, monthly_budget_usd, monthly_spend_usd, last_check_at, created_at, updated_at FROM providers ORDER BY id
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.EnvKey,
			&i.DocsUrl,
			&i.Status,
			&i.MonthlyBudgetUsd,
			&i.MonthlySpendUsd,
			&i.LastCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderStatus = `-- name: UpdateProviderStatus :exec
UPDATE providers SET status = $2, last_check_at = NOW() WHERE id = $1
`

type UpdateProviderStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateProviderStatus(ctx context.Context, arg UpdateProviderStatusParams) error {
	_, err := q.db.Exec(ctx, updateProviderStatus, arg.ID, arg.Status)
	return err
}
