// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registries.sql

package store

import (
	"context"
	"database/sql"
)

const countActiveMCPConnections = `-- name: CountActiveMCPConnections :one
SELECT COUNT(*) AS total FROM mcp_connections WHERE status = 'active'
`

func (q *Queries) CountActiveMCPConnections(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveMCPConnections)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAgents = `-- name: CountAgents :one
SELECT COUNT(*) AS total FROM agents WHERE status = 'active'
`

func (q *Queries) CountAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgents)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAvailableRuntimes = `-- name: CountAvailableRuntimes :one
SELECT COUNT(*) AS total FROM agent_runtimes WHERE status IN ('detected', 'configured')
`

func (q *Queries) CountAvailableRuntimes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAvailableRuntimes)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDetectedCLITools = `-- name: CountDetectedCLITools :one
SELECT COUNT(*) AS total FROM cli_tools WHERE status = 'detected'
`

func (q *Queries) CountDetectedCLITools(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDetectedCLITools)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countProjects = `-- name: CountProjects :one

SELECT COUNT(*) AS total FROM projects WHERE status != 'archived'
`

// Queries for basic registries.
// Solo lectura + counts en Fase 2. CRUD completo viene en Fase 3.
func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSkills = `-- name: CountSkills :one
SELECT COUNT(*) AS total FROM skills WHERE status = 'active'
`

func (q *Queries) CountSkills(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSkills)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    id, slug, name, role, description, runtime_id, runtime_config,
    system_prompt, allowed_tools, allowed_projects, risk_level,
    is_lead, is_meta, status
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, 0, ?)
RETURNING id, slug, name, role, description, runtime_id, runtime_config, system_prompt,
          allowed_tools, allowed_projects, risk_level, is_lead, is_meta, status,
          created_at, updated_at
`

type CreateAgentParams struct {
	ID              string         `json:"id"`
	Slug            string         `json:"slug"`
	Name            string         `json:"name"`
	Role            sql.NullString `json:"role"`
	Description     sql.NullString `json:"description"`
	RuntimeID       sql.NullString `json:"runtime_id"`
	RuntimeConfig   string         `json:"runtime_config"`
	SystemPrompt    sql.NullString `json:"system_prompt"`
	AllowedTools    string         `json:"allowed_tools"`
	AllowedProjects string         `json:"allowed_projects"`
	RiskLevel       string         `json:"risk_level"`
	Status          string         `json:"status"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Role,
		arg.Description,
		arg.RuntimeID,
		arg.RuntimeConfig,
		arg.SystemPrompt,
		arg.AllowedTools,
		arg.AllowedProjects,
		arg.RiskLevel,
		arg.Status,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.RuntimeID,
		&i.RuntimeConfig,
		&i.SystemPrompt,
		&i.AllowedTools,
		&i.AllowedProjects,
		&i.RiskLevel,
		&i.IsLead,
		&i.IsMeta,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCLIToolInstall = `-- name: CreateCLIToolInstall :one

INSERT INTO cli_tool_installs (id, cli_tool_id, install_command)
VALUES (lower(hex(randomblob(16))), ?, ?)
RETURNING id, cli_tool_id, install_command, status, reason, output,
          requested_at, decided_at, completed_at
`

type CreateCLIToolInstallParams struct {
	CliToolID      string `json:"cli_tool_id"`
	InstallCommand string `json:"install_command"`
}

// Instalacion gobernada de CLIs (Etapa 2): el request queda pending_approval y
// solo se ejecuta tras un approve explicito (mismo modelo HITL que run_approvals).
// NOTA: sin acentos en comentarios de queries -- sqlc desplaza offsets con
// caracteres multibyte y trunca el SQL generado.
func (q *Queries) CreateCLIToolInstall(ctx context.Context, arg CreateCLIToolInstallParams) (CliToolInstall, error) {
	row := q.db.QueryRowContext(ctx, createCLIToolInstall, arg.CliToolID, arg.InstallCommand)
	var i CliToolInstall
	err := row.Scan(
		&i.ID,
		&i.CliToolID,
		&i.InstallCommand,
		&i.Status,
		&i.Reason,
		&i.Output,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.CompletedAt,
	)
	return i, err
}

const decideCLIToolInstall = `-- name: DecideCLIToolInstall :one
UPDATE cli_tool_installs
SET status = ?, reason = ?, decided_at = CURRENT_TIMESTAMP
WHERE id = ? AND status = 'pending_approval'
RETURNING id, cli_tool_id, install_command, status, reason, output,
          requested_at, decided_at, completed_at
`

type DecideCLIToolInstallParams struct {
	Status string         `json:"status"`
	Reason sql.NullString `json:"reason"`
	ID     string         `json:"id"`
}

func (q *Queries) DecideCLIToolInstall(ctx context.Context, arg DecideCLIToolInstallParams) (CliToolInstall, error) {
	row := q.db.QueryRowContext(ctx, decideCLIToolInstall, arg.Status, arg.Reason, arg.ID)
	var i CliToolInstall
	err := row.Scan(
		&i.ID,
		&i.CliToolID,
		&i.InstallCommand,
		&i.Status,
		&i.Reason,
		&i.Output,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.CompletedAt,
	)
	return i, err
}

const finishCLIToolInstall = `-- name: FinishCLIToolInstall :one
UPDATE cli_tool_installs
SET status = ?, output = ?, completed_at = CURRENT_TIMESTAMP
WHERE id = ? AND status = 'running'
RETURNING id, cli_tool_id, install_command, status, reason, output,
          requested_at, decided_at, completed_at
`

type FinishCLIToolInstallParams struct {
	Status string         `json:"status"`
	Output sql.NullString `json:"output"`
	ID     string         `json:"id"`
}

func (q *Queries) FinishCLIToolInstall(ctx context.Context, arg FinishCLIToolInstallParams) (CliToolInstall, error) {
	row := q.db.QueryRowContext(ctx, finishCLIToolInstall, arg.Status, arg.Output, arg.ID)
	var i CliToolInstall
	err := row.Scan(
		&i.ID,
		&i.CliToolID,
		&i.InstallCommand,
		&i.Status,
		&i.Reason,
		&i.Output,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAgentRuntime = `-- name: GetAgentRuntime :one
SELECT id, name, kind, status, binary_path, version, endpoint_url, risk_level,
       requires_auth, capabilities, config_schema, detected_at, created_at, updated_at
FROM agent_runtimes WHERE id = ?
`

func (q *Queries) GetAgentRuntime(ctx context.Context, id string) (AgentRuntime, error) {
	row := q.db.QueryRowContext(ctx, getAgentRuntime, id)
	var i AgentRuntime
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.BinaryPath,
		&i.Version,
		&i.EndpointUrl,
		&i.RiskLevel,
		&i.RequiresAuth,
		&i.Capabilities,
		&i.ConfigSchema,
		&i.DetectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCLITool = `-- name: GetCLITool :one
SELECT id, name, command, kind, detected_path, version, runtime_id, status,
       risk_level, requires_auth, capabilities, install_command, install_url,
       last_detected_at, created_at, updated_at
FROM cli_tools WHERE id = ?
`

func (q *Queries) GetCLITool(ctx context.Context, id string) (CliTool, error) {
	row := q.db.QueryRowContext(ctx, getCLITool, id)
	var i CliTool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.Kind,
		&i.DetectedPath,
		&i.Version,
		&i.RuntimeID,
		&i.Status,
		&i.RiskLevel,
		&i.RequiresAuth,
		&i.Capabilities,
		&i.InstallCommand,
		&i.InstallUrl,
		&i.LastDetectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCLIToolInstall = `-- name: GetCLIToolInstall :one
SELECT id, cli_tool_id, install_command, status, reason, output,
       requested_at, decided_at, completed_at
FROM cli_tool_installs WHERE id = ?
`

func (q *Queries) GetCLIToolInstall(ctx context.Context, id string) (CliToolInstall, error) {
	row := q.db.QueryRowContext(ctx, getCLIToolInstall, id)
	var i CliToolInstall
	err := row.Scan(
		&i.ID,
		&i.CliToolID,
		&i.InstallCommand,
		&i.Status,
		&i.Reason,
		&i.Output,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, kind, env_key, docs_url, status, monthly_budget_usd,
       monthly_spend_usd, last_check_at, created_at, updated_at
FROM providers WHERE id = ?
`

func (q *Queries) GetProvider(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.EnvKey,
		&i.DocsUrl,
		&i.Status,
		&i.MonthlyBudgetUsd,
		&i.MonthlySpendUsd,
		&i.LastCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentRuntimes = `-- name: ListAgentRuntimes :many
SELECT id, name, kind, status, binary_path, version, endpoint_url, risk_level,
       requires_auth, capabilities, config_schema, detected_at, created_at, updated_at
FROM agent_runtimes ORDER BY id
`

func (q *Queries) ListAgentRuntimes(ctx context.Context) ([]AgentRuntime, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRuntimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRuntime{}
	for rows.Next() {
		var i AgentRuntime
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Status,
			&i.BinaryPath,
			&i.Version,
			&i.EndpointUrl,
			&i.RiskLevel,
			&i.RequiresAuth,
			&i.Capabilities,
			&i.ConfigSchema,
			&i.DetectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, slug, name, role, description, runtime_id, runtime_config, system_prompt,
       allowed_tools, allowed_projects, risk_level, is_lead, is_meta, status,
       created_at, updated_at
FROM agents ORDER BY id
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.RuntimeID,
			&i.RuntimeConfig,
			&i.SystemPrompt,
			&i.AllowedTools,
			&i.AllowedProjects,
			&i.RiskLevel,
			&i.IsLead,
			&i.IsMeta,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCLIToolInstalls = `-- name: ListCLIToolInstalls :many
SELECT id, cli_tool_id, install_command, status, reason, output,
       requested_at, decided_at, completed_at
FROM cli_tool_installs
WHERE cli_tool_id = ?
ORDER BY requested_at DESC, id
`

func (q *Queries) ListCLIToolInstalls(ctx context.Context, cliToolID string) ([]CliToolInstall, error) {
	rows, err := q.db.QueryContext(ctx, listCLIToolInstalls, cliToolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CliToolInstall{}
	for rows.Next() {
		var i CliToolInstall
		if err := rows.Scan(
			&i.ID,
			&i.CliToolID,
			&i.InstallCommand,
			&i.Status,
			&i.Reason,
			&i.Output,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCLITools = `-- name: ListCLITools :many
SELECT id, name, command, kind, detected_path, version, runtime_id, status,
       risk_level, requires_auth, capabilities, install_command, install_url,
       last_detected_at, created_at, updated_at
FROM cli_tools ORDER BY id
`

func (q *Queries) ListCLITools(ctx context.Context) ([]CliTool, error) {
	rows, err := q.db.QueryContext(ctx, listCLITools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CliTool{}
	for rows.Next() {
		var i CliTool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Command,
			&i.Kind,
			&i.DetectedPath,
			&i.Version,
			&i.RuntimeID,
			&i.Status,
			&i.RiskLevel,
			&i.RequiresAuth,
			&i.Capabilities,
			&i.InstallCommand,
			&i.InstallUrl,
			&i.LastDetectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, kind, env_key, docs_url, status, monthly_budget_usd,
       monthly_spend_usd, last_check_at, created_at, updated_at
FROM providers ORDER BY id
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.EnvKey,
			&i.DocsUrl,
			&i.Status,
			&i.MonthlyBudgetUsd,
			&i.MonthlySpendUsd,
			&i.LastCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id, slug, name, description, category, risk_level, inputs, outputs, steps,
       compatible_agents, compatible_runtimes, source, source_id, source_ref, version,
       status, prompt_template, lifecycle, created_at, updated_at
FROM skills ORDER BY id
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.RiskLevel,
			&i.Inputs,
			&i.Outputs,
			&i.Steps,
			&i.CompatibleAgents,
			&i.CompatibleRuntimes,
			&i.Source,
			&i.SourceID,
			&i.SourceRef,
			&i.Version,
			&i.Status,
			&i.PromptTemplate,
			&i.Lifecycle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentRuntimeDetection = `-- name: UpdateAgentRuntimeDetection :one
UPDATE agent_runtimes
SET status = ?, binary_path = ?, version = ?, detected_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, kind, status, binary_path, version, endpoint_url, risk_level,
          requires_auth, capabilities, config_schema, detected_at, created_at, updated_at
`

type UpdateAgentRuntimeDetectionParams struct {
	Status     string         `json:"status"`
	BinaryPath sql.NullString `json:"binary_path"`
	Version    sql.NullString `json:"version"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateAgentRuntimeDetection(ctx context.Context, arg UpdateAgentRuntimeDetectionParams) (AgentRuntime, error) {
	row := q.db.QueryRowContext(ctx, updateAgentRuntimeDetection,
		arg.Status,
		arg.BinaryPath,
		arg.Version,
		arg.ID,
	)
	var i AgentRuntime
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.BinaryPath,
		&i.Version,
		&i.EndpointUrl,
		&i.RiskLevel,
		&i.RequiresAuth,
		&i.Capabilities,
		&i.ConfigSchema,
		&i.DetectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProviderStatus = `-- name: UpdateProviderStatus :exec
UPDATE providers SET status = ?, last_check_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateProviderStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateProviderStatus(ctx context.Context, arg UpdateProviderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderStatus, arg.Status, arg.ID)
	return err
}

const upsertCLIToolDetection = `-- name: UpsertCLIToolDetection :one
INSERT INTO cli_tools (
    id, name, command, kind, detected_path, version, runtime_id, status,
    risk_level, requires_auth, capabilities, install_command, install_url, last_detected_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    command = EXCLUDED.command,
    kind = EXCLUDED.kind,
    detected_path = EXCLUDED.detected_path,
    version = EXCLUDED.version,
    runtime_id = EXCLUDED.runtime_id,
    status = EXCLUDED.status,
    risk_level = EXCLUDED.risk_level,
    requires_auth = EXCLUDED.requires_auth,
    capabilities = EXCLUDED.capabilities,
    install_command = EXCLUDED.install_command,
    install_url = EXCLUDED.install_url,
    last_detected_at = CURRENT_TIMESTAMP
RETURNING id, name, command, kind, detected_path, version, runtime_id, status,
          risk_level, requires_auth, capabilities, install_command, install_url,
          last_detected_at, created_at, updated_at
`

type UpsertCLIToolDetectionParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Command        string         `json:"command"`
	Kind           string         `json:"kind"`
	DetectedPath   sql.NullString `json:"detected_path"`
	Version        sql.NullString `json:"version"`
	RuntimeID      sql.NullString `json:"runtime_id"`
	Status         string         `json:"status"`
	RiskLevel      string         `json:"risk_level"`
	RequiresAuth   int64          `json:"requires_auth"`
	Capabilities   string         `json:"capabilities"`
	InstallCommand sql.NullString `json:"install_command"`
	InstallUrl     sql.NullString `json:"install_url"`
}

func (q *Queries) UpsertCLIToolDetection(ctx context.Context, arg UpsertCLIToolDetectionParams) (CliTool, error) {
	row := q.db.QueryRowContext(ctx, upsertCLIToolDetection,
		arg.ID,
		arg.Name,
		arg.Command,
		arg.Kind,
		arg.DetectedPath,
		arg.Version,
		arg.RuntimeID,
		arg.Status,
		arg.RiskLevel,
		arg.RequiresAuth,
		arg.Capabilities,
		arg.InstallCommand,
		arg.InstallUrl,
	)
	var i CliTool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.Kind,
		&i.DetectedPath,
		&i.Version,
		&i.RuntimeID,
		&i.Status,
		&i.RiskLevel,
		&i.RequiresAuth,
		&i.Capabilities,
		&i.InstallCommand,
		&i.InstallUrl,
		&i.LastDetectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
