// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepository = `-- name: CreateRepository :one

INSERT INTO repositories (id, project_id, kind, name, remote_url, credential_ref, default_branch, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, kind, name, remote_url, credential_ref, default_branch, metadata, created_at, updated_at
`

type CreateRepositoryParams struct {
	ID            string      `json:"id"`
	ProjectID     string      `json:"project_id"`
	Kind          string      `json:"kind"`
	Name          string      `json:"name"`
	RemoteUrl     pgtype.Text `json:"remote_url"`
	CredentialRef pgtype.Text `json:"credential_ref"`
	DefaultBranch string      `json:"default_branch"`
	Metadata      []byte      `json:"metadata"`
}

// Repositories CRUD
func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.ID,
		arg.ProjectID,
		arg.Kind,
		arg.Name,
		arg.RemoteUrl,
		arg.CredentialRef,
		arg.DefaultBranch,
		arg.Metadata,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.RemoteUrl,
		&i.CredentialRef,
		&i.DefaultBranch,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :one
DELETE FROM repositories WHERE id = $1
RETURNING id, project_id, kind, name, remote_url, credential_ref, default_branch, metadata, created_at, updated_at
`

func (q *Queries) DeleteRepository(ctx context.Context, id string) (Repository, error) {
	row := q.db.QueryRow(ctx, deleteRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.RemoteUrl,
		&i.CredentialRef,
		&i.DefaultBranch,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepository = `-- name: GetRepository :one
SELECT id, project_id, kind, name, remote_url, credential_ref, default_branch, metadata, created_at, updated_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepository(ctx context.Context, id string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.RemoteUrl,
		&i.CredentialRef,
		&i.DefaultBranch,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, project_id, kind, name, remote_url, credential_ref, default_branch, metadata, created_at, updated_at FROM repositories
ORDER BY created_at DESC
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Name,
			&i.RemoteUrl,
			&i.CredentialRef,
			&i.DefaultBranch,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByProject = `-- name: ListRepositoriesByProject :many
SELECT id, project_id, kind, name, remote_url, credential_ref, default_branch, metadata, created_at, updated_at FROM repositories
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRepositoriesByProject(ctx context.Context, projectID string) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Name,
			&i.RemoteUrl,
			&i.CredentialRef,
			&i.DefaultBranch,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
