// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendRunLog = `-- name: AppendRunLog :one
INSERT INTO run_logs (run_id, stream, message)
VALUES ($1, $2, $3)
RETURNING id, run_id, stream, message, created_at
`

type AppendRunLogParams struct {
	RunID   pgtype.UUID `json:"run_id"`
	Stream  string      `json:"stream"`
	Message string      `json:"message"`
}

func (q *Queries) AppendRunLog(ctx context.Context, arg AppendRunLogParams) (RunLog, error) {
	row := q.db.QueryRow(ctx, appendRunLog, arg.RunID, arg.Stream, arg.Message)
	var i RunLog
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Stream,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const cancelRun = `-- name: CancelRun :one
UPDATE runs
SET status = 'cancelled',
    completed_at = COALESCE(completed_at, NOW())
WHERE id = $1
  AND status IN ('draft', 'awaiting_approval', 'queued', 'running')
RETURNING id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at
`

func (q *Queries) CancelRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, cancelRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimNextQueuedRun = `-- name: ClaimNextQueuedRun :one
UPDATE runs
SET status = 'running',
    started_at = NOW()
WHERE id = (
    SELECT id
    FROM runs
    WHERE status = 'queued'
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at
`

func (q *Queries) ClaimNextQueuedRun(ctx context.Context) (Run, error) {
	row := q.db.QueryRow(ctx, claimNextQueuedRun)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimQueuedRunByID = `-- name: ClaimQueuedRunByID :one
UPDATE runs
SET status = 'running',
    started_at = NOW()
WHERE id = $1
  AND status = 'queued'
RETURNING id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at
`

func (q *Queries) ClaimQueuedRunByID(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, claimQueuedRunByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeRun = `-- name: CompleteRun :one
UPDATE runs
SET status = 'succeeded',
    result_summary = $2,
    completed_at = NOW(),
    error_message = NULL
WHERE id = $1
RETURNING id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at
`

type CompleteRunParams struct {
	ID            pgtype.UUID `json:"id"`
	ResultSummary pgtype.Text `json:"result_summary"`
}

func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, completeRun, arg.ID, arg.ResultSummary)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one

INSERT INTO runs (
    project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id,
    prompt, requested_network, network_enabled, status, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, false, 'awaiting_approval', '{}'::jsonb)
RETURNING id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at
`

type CreateRunParams struct {
	ProjectID        string      `json:"project_id"`
	TaskID           string      `json:"task_id"`
	AgentID          string      `json:"agent_id"`
	SkillID          pgtype.Text `json:"skill_id"`
	RuntimeAdapterID string      `json:"runtime_adapter_id"`
	RepositoryID     pgtype.Text `json:"repository_id"`
	Prompt           string      `json:"prompt"`
	RequestedNetwork bool        `json:"requested_network"`
}

// Run proposal and approval queries.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ProjectID,
		arg.TaskID,
		arg.AgentID,
		arg.SkillID,
		arg.RuntimeAdapterID,
		arg.RepositoryID,
		arg.Prompt,
		arg.RequestedNetwork,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRunApproval = `-- name: CreateRunApproval :one
INSERT INTO run_approvals (run_id, kind, decision, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, kind, decision, reason, decided_at
`

type CreateRunApprovalParams struct {
	RunID    pgtype.UUID `json:"run_id"`
	Kind     string      `json:"kind"`
	Decision string      `json:"decision"`
	Reason   pgtype.Text `json:"reason"`
}

func (q *Queries) CreateRunApproval(ctx context.Context, arg CreateRunApprovalParams) (RunApproval, error) {
	row := q.db.QueryRow(ctx, createRunApproval,
		arg.RunID,
		arg.Kind,
		arg.Decision,
		arg.Reason,
	)
	var i RunApproval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Decision,
		&i.Reason,
		&i.DecidedAt,
	)
	return i, err
}

const enableRunNetwork = `-- name: EnableRunNetwork :one
UPDATE runs
SET network_enabled = true
WHERE id = $1
RETURNING id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at
`

func (q *Queries) EnableRunNetwork(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, enableRunNetwork, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failRun = `-- name: FailRun :one
UPDATE runs
SET status = 'failed',
    result_summary = $2,
    error_message = $3,
    completed_at = NOW()
WHERE id = $1
RETURNING id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at
`

type FailRunParams struct {
	ID            pgtype.UUID `json:"id"`
	ResultSummary pgtype.Text `json:"result_summary"`
	ErrorMessage  pgtype.Text `json:"error_message"`
}

func (q *Queries) FailRun(ctx context.Context, arg FailRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, failRun, arg.ID, arg.ResultSummary, arg.ErrorMessage)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunLogs = `-- name: ListRunLogs :many
SELECT id, run_id, stream, message, created_at FROM run_logs
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRunLogs(ctx context.Context, runID pgtype.UUID) ([]RunLog, error) {
	rows, err := q.db.Query(ctx, listRunLogs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunLog{}
	for rows.Next() {
		var i RunLog
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Stream,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at FROM runs
ORDER BY created_at DESC
`

func (q *Queries) ListRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.AgentID,
			&i.SkillID,
			&i.RuntimeAdapterID,
			&i.RepositoryID,
			&i.Prompt,
			&i.RequestedNetwork,
			&i.NetworkEnabled,
			&i.Status,
			&i.BranchName,
			&i.ResultSummary,
			&i.ErrorMessage,
			&i.EstimatedCostUsd,
			&i.Metadata,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at FROM runs
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRunsByProject(ctx context.Context, projectID string) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.AgentID,
			&i.SkillID,
			&i.RuntimeAdapterID,
			&i.RepositoryID,
			&i.Prompt,
			&i.RequestedNetwork,
			&i.NetworkEnabled,
			&i.Status,
			&i.BranchName,
			&i.ResultSummary,
			&i.ErrorMessage,
			&i.EstimatedCostUsd,
			&i.Metadata,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunBranchAndMetadata = `-- name: UpdateRunBranchAndMetadata :one
UPDATE runs
SET branch_name = $2,
    metadata = $3
WHERE id = $1
RETURNING id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at
`

type UpdateRunBranchAndMetadataParams struct {
	ID         pgtype.UUID `json:"id"`
	BranchName pgtype.Text `json:"branch_name"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) UpdateRunBranchAndMetadata(ctx context.Context, arg UpdateRunBranchAndMetadataParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunBranchAndMetadata, arg.ID, arg.BranchName, arg.Metadata)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $2
WHERE id = $1
RETURNING id, project_id, task_id, agent_id, skill_id, runtime_adapter_id, repository_id, prompt, requested_network, network_enabled, status, branch_name, result_summary, error_message, estimated_cost_usd, metadata, started_at, completed_at, created_at, updated_at
`

type UpdateRunStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus, arg.ID, arg.Status)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.SkillID,
		&i.RuntimeAdapterID,
		&i.RepositoryID,
		&i.Prompt,
		&i.RequestedNetwork,
		&i.NetworkEnabled,
		&i.Status,
		&i.BranchName,
		&i.ResultSummary,
		&i.ErrorMessage,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
