// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package store

import (
	"context"
)

const insertSystemLog = `-- name: InsertSystemLog :exec
INSERT INTO system_logs (id, level, source, message, context)
VALUES (lower(hex(randomblob(16))), ?, ?, ?, ?)
`

type InsertSystemLogParams struct {
	Level   string `json:"level"`
	Source  string `json:"source"`
	Message string `json:"message"`
	Context string `json:"context"`
}

func (q *Queries) InsertSystemLog(ctx context.Context, arg InsertSystemLogParams) error {
	_, err := q.db.ExecContext(ctx, insertSystemLog,
		arg.Level,
		arg.Source,
		arg.Message,
		arg.Context,
	)
	return err
}

const pingDB = `-- name: PingDB :one

SELECT 1 AS ok
`

// Queries de sistema: healthchecks, logs.
func (q *Queries) PingDB(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, pingDB)
	var ok int64
	err := row.Scan(&ok)
	return ok, err
}

const recentSystemLogs = `-- name: RecentSystemLogs :many
SELECT id, level, source, message, context, created_at FROM system_logs
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) RecentSystemLogs(ctx context.Context, limit int64) ([]SystemLog, error) {
	rows, err := q.db.QueryContext(ctx, recentSystemLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemLog{}
	for rows.Next() {
		var i SystemLog
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Source,
			&i.Message,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
