// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUsageEvent = `-- name: CreateUsageEvent :one

INSERT INTO usage_events (
    run_id, provider_id, model_id, project_id, agent_id, skill_id,
    input_tokens, output_tokens, cached_tokens, request_count, estimated_cost_usd
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, run_id, provider_id, model_id, project_id, agent_id, skill_id, input_tokens, output_tokens, cached_tokens, request_count, estimated_cost_usd, created_at
`

type CreateUsageEventParams struct {
	RunID            pgtype.UUID    `json:"run_id"`
	ProviderID       pgtype.Text    `json:"provider_id"`
	ModelID          pgtype.Text    `json:"model_id"`
	ProjectID        pgtype.Text    `json:"project_id"`
	AgentID          pgtype.Text    `json:"agent_id"`
	SkillID          pgtype.Text    `json:"skill_id"`
	InputTokens      int32          `json:"input_tokens"`
	OutputTokens     int32          `json:"output_tokens"`
	CachedTokens     int32          `json:"cached_tokens"`
	RequestCount     int32          `json:"request_count"`
	EstimatedCostUsd pgtype.Numeric `json:"estimated_cost_usd"`
}

// Queries para eventos de consumo y uso (usage_events)
func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, createUsageEvent,
		arg.RunID,
		arg.ProviderID,
		arg.ModelID,
		arg.ProjectID,
		arg.AgentID,
		arg.SkillID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.RequestCount,
		arg.EstimatedCostUsd,
	)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ProviderID,
		&i.ModelID,
		&i.ProjectID,
		&i.AgentID,
		&i.SkillID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.RequestCount,
		&i.EstimatedCostUsd,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageByRun = `-- name: GetUsageByRun :many
SELECT id, run_id, provider_id, model_id, project_id, agent_id, skill_id, input_tokens, output_tokens, cached_tokens, request_count, estimated_cost_usd, created_at FROM usage_events WHERE run_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetUsageByRun(ctx context.Context, runID pgtype.UUID) ([]UsageEvent, error) {
	rows, err := q.db.Query(ctx, getUsageByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageEvent{}
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ProviderID,
			&i.ModelID,
			&i.ProjectID,
			&i.AgentID,
			&i.SkillID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.RequestCount,
			&i.EstimatedCostUsd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageOverview = `-- name: GetUsageOverview :many
SELECT 
    ue.project_id,
    COALESCE(p.name, ue.project_id) AS project_name,
    p.monthly_budget_usd AS project_monthly_budget_usd,
    ue.agent_id,
    ue.model_id,
    ue.provider_id,
    SUM(ue.input_tokens)::bigint AS total_input_tokens,
    SUM(ue.output_tokens)::bigint AS total_output_tokens,
    SUM(ue.cached_tokens)::bigint AS total_cached_tokens,
    SUM(ue.request_count)::bigint AS total_requests,
    COALESCE(SUM(ue.estimated_cost_usd), 0)::numeric(10, 6) AS total_cost_usd
FROM usage_events ue
LEFT JOIN projects p ON p.slug = ue.project_id OR p.id::text = ue.project_id
GROUP BY ue.project_id, p.name, p.monthly_budget_usd, ue.agent_id, ue.model_id, ue.provider_id
ORDER BY total_cost_usd DESC
`

type GetUsageOverviewRow struct {
	ProjectID               pgtype.Text    `json:"project_id"`
	ProjectName             string         `json:"project_name"`
	ProjectMonthlyBudgetUsd pgtype.Numeric `json:"project_monthly_budget_usd"`
	AgentID                 pgtype.Text    `json:"agent_id"`
	ModelID                 pgtype.Text    `json:"model_id"`
	ProviderID              pgtype.Text    `json:"provider_id"`
	TotalInputTokens        int64          `json:"total_input_tokens"`
	TotalOutputTokens       int64          `json:"total_output_tokens"`
	TotalCachedTokens       int64          `json:"total_cached_tokens"`
	TotalRequests           int64          `json:"total_requests"`
	TotalCostUsd            pgtype.Numeric `json:"total_cost_usd"`
}

func (q *Queries) GetUsageOverview(ctx context.Context) ([]GetUsageOverviewRow, error) {
	rows, err := q.db.Query(ctx, getUsageOverview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageOverviewRow{}
	for rows.Next() {
		var i GetUsageOverviewRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectMonthlyBudgetUsd,
			&i.AgentID,
			&i.ModelID,
			&i.ProviderID,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCachedTokens,
			&i.TotalRequests,
			&i.TotalCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
