// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package store

import (
	"context"
	"database/sql"
)

const createUsageEvent = `-- name: CreateUsageEvent :one

INSERT INTO usage_events (
    id, run_id, provider_id, model_id, project_id, agent_id, skill_id,
    input_tokens, output_tokens, cached_tokens, request_count, estimated_cost_usd
)
VALUES (lower(hex(randomblob(16))), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, run_id, provider_id, model_id, project_id, agent_id, skill_id,
          input_tokens, output_tokens, cached_tokens, request_count,
          estimated_cost_usd, created_at
`

type CreateUsageEventParams struct {
	RunID            sql.NullString `json:"run_id"`
	ProviderID       sql.NullString `json:"provider_id"`
	ModelID          sql.NullString `json:"model_id"`
	ProjectID        sql.NullString `json:"project_id"`
	AgentID          sql.NullString `json:"agent_id"`
	SkillID          sql.NullString `json:"skill_id"`
	InputTokens      int64          `json:"input_tokens"`
	OutputTokens     int64          `json:"output_tokens"`
	CachedTokens     int64          `json:"cached_tokens"`
	RequestCount     int64          `json:"request_count"`
	EstimatedCostUsd float64        `json:"estimated_cost_usd"`
}

// Queries para eventos de consumo y uso (usage_events)
func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRowContext(ctx, createUsageEvent,
		arg.RunID,
		arg.ProviderID,
		arg.ModelID,
		arg.ProjectID,
		arg.AgentID,
		arg.SkillID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.RequestCount,
		arg.EstimatedCostUsd,
	)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ProviderID,
		&i.ModelID,
		&i.ProjectID,
		&i.AgentID,
		&i.SkillID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.RequestCount,
		&i.EstimatedCostUsd,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageByRun = `-- name: GetUsageByRun :many
SELECT id, run_id, provider_id, model_id, project_id, agent_id, skill_id,
       input_tokens, output_tokens, cached_tokens, request_count,
       estimated_cost_usd, created_at
FROM usage_events WHERE run_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetUsageByRun(ctx context.Context, runID sql.NullString) ([]UsageEvent, error) {
	rows, err := q.db.QueryContext(ctx, getUsageByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageEvent{}
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ProviderID,
			&i.ModelID,
			&i.ProjectID,
			&i.AgentID,
			&i.SkillID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.RequestCount,
			&i.EstimatedCostUsd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageOverview = `-- name: GetUsageOverview :many
SELECT 
    ue.project_id,
    COALESCE(p.name, ue.project_id) AS project_name,
    p.monthly_budget_usd AS project_monthly_budget_usd,
    ue.agent_id,
    ue.model_id,
    ue.provider_id,
    SUM(ue.input_tokens) AS total_input_tokens,
    SUM(ue.output_tokens) AS total_output_tokens,
    SUM(ue.cached_tokens) AS total_cached_tokens,
    SUM(ue.request_count) AS total_requests,
    COALESCE(SUM(ue.estimated_cost_usd), 0) AS total_cost_usd
FROM usage_events ue
LEFT JOIN projects p ON p.slug = ue.project_id OR p.id = ue.project_id
GROUP BY ue.project_id, p.name, p.monthly_budget_usd, ue.agent_id, ue.model_id, ue.provider_id
ORDER BY total_cost_usd DESC
`

type GetUsageOverviewRow struct {
	ProjectID               sql.NullString  `json:"project_id"`
	ProjectName             string          `json:"project_name"`
	ProjectMonthlyBudgetUsd sql.NullFloat64 `json:"project_monthly_budget_usd"`
	AgentID                 sql.NullString  `json:"agent_id"`
	ModelID                 sql.NullString  `json:"model_id"`
	ProviderID              sql.NullString  `json:"provider_id"`
	TotalInputTokens        sql.NullFloat64 `json:"total_input_tokens"`
	TotalOutputTokens       sql.NullFloat64 `json:"total_output_tokens"`
	TotalCachedTokens       sql.NullFloat64 `json:"total_cached_tokens"`
	TotalRequests           sql.NullFloat64 `json:"total_requests"`
	TotalCostUsd            interface{}     `json:"total_cost_usd"`
}

func (q *Queries) GetUsageOverview(ctx context.Context) ([]GetUsageOverviewRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsageOverview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageOverviewRow{}
	for rows.Next() {
		var i GetUsageOverviewRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectMonthlyBudgetUsd,
			&i.AgentID,
			&i.ModelID,
			&i.ProviderID,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCachedTokens,
			&i.TotalRequests,
			&i.TotalCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
