// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDomain = `-- name: CreateDomain :one

INSERT INTO domains (id, slug, name, description, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, name, description, status, metadata, created_at, updated_at
`

type CreateDomainParams struct {
	ID          string      `json:"id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Metadata    []byte      `json:"metadata"`
}

// Work Board CRUD: domains, projects, goals and tasks.
func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (project_id, title, description, status, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, title, description, status, metadata, created_at, updated_at
`

type CreateGoalParams struct {
	ProjectID   string      `json:"project_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, slug, name, description, domain_id, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, name, description, status, owner_agent_id, monthly_budget_usd, metadata, created_at, updated_at, domain_id
`

type CreateProjectParams struct {
	ID          string      `json:"id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	DomainID    pgtype.Text `json:"domain_id"`
	Status      string      `json:"status"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.DomainID,
		arg.Status,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerAgentID,
		&i.MonthlyBudgetUsd,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    project_id, goal_id, title, description, assigned_agent_id, status,
    board_position, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, goal_id, title, description, assigned_agent_id, status, board_position, metadata, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID       string      `json:"project_id"`
	GoalID          pgtype.Text `json:"goal_id"`
	Title           string      `json:"title"`
	Description     pgtype.Text `json:"description"`
	AssignedAgentID pgtype.Text `json:"assigned_agent_id"`
	Status          string      `json:"status"`
	BoardPosition   int32       `json:"board_position"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.GoalID,
		arg.Title,
		arg.Description,
		arg.AssignedAgentID,
		arg.Status,
		arg.BoardPosition,
		arg.Metadata,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoalID,
		&i.Title,
		&i.Description,
		&i.AssignedAgentID,
		&i.Status,
		&i.BoardPosition,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one
SELECT id, slug, name, description, status, metadata, created_at, updated_at FROM domains WHERE id = $1
`

func (q *Queries) GetDomain(ctx context.Context, id string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, project_id, title, description, status, metadata, created_at, updated_at FROM goals WHERE id = $1
`

func (q *Queries) GetGoal(ctx context.Context, id string) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, slug, name, description, status, owner_agent_id, monthly_budget_usd, metadata, created_at, updated_at, domain_id FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerAgentID,
		&i.MonthlyBudgetUsd,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, goal_id, title, description, assigned_agent_id, status, board_position, metadata, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoalID,
		&i.Title,
		&i.Description,
		&i.AssignedAgentID,
		&i.Status,
		&i.BoardPosition,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT id, slug, name, description, status, metadata, created_at, updated_at FROM domains
WHERE status != 'archived'
ORDER BY created_at DESC
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByProject = `-- name: ListGoalsByProject :many
SELECT id, project_id, title, description, status, metadata, created_at, updated_at FROM goals
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGoalsByProject(ctx context.Context, projectID string) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, description, status, owner_agent_id, monthly_budget_usd, metadata, created_at, updated_at, domain_id FROM projects
WHERE status != 'archived'
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.OwnerAgentID,
			&i.MonthlyBudgetUsd,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, goal_id, title, description, assigned_agent_id, status, board_position, metadata, created_at, updated_at FROM tasks
WHERE project_id = $1
ORDER BY status, board_position, created_at DESC
`

func (q *Queries) ListTasksByProject(ctx context.Context, projectID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.GoalID,
			&i.Title,
			&i.Description,
			&i.AssignedAgentID,
			&i.Status,
			&i.BoardPosition,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomain = `-- name: UpdateDomain :one
UPDATE domains
SET name = $2, description = $3, status = $4, metadata = $5
WHERE id = $1
RETURNING id, slug, name, description, status, metadata, created_at, updated_at
`

type UpdateDomainParams struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomain,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET title = $2, description = $3, status = $4, metadata = $5
WHERE id = $1
RETURNING id, project_id, title, description, status, metadata, created_at, updated_at
`

type UpdateGoalParams struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3, domain_id = $4, status = $5, metadata = $6
WHERE id = $1
RETURNING id, slug, name, description, status, owner_agent_id, monthly_budget_usd, metadata, created_at, updated_at, domain_id
`

type UpdateProjectParams struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	DomainID    pgtype.Text `json:"domain_id"`
	Status      string      `json:"status"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DomainID,
		arg.Status,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerAgentID,
		&i.MonthlyBudgetUsd,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET goal_id = $2, title = $3, description = $4, assigned_agent_id = $5,
    status = $6, board_position = $7, metadata = $8
WHERE id = $1
RETURNING id, project_id, goal_id, title, description, assigned_agent_id, status, board_position, metadata, created_at, updated_at
`

type UpdateTaskParams struct {
	ID              string      `json:"id"`
	GoalID          pgtype.Text `json:"goal_id"`
	Title           string      `json:"title"`
	Description     pgtype.Text `json:"description"`
	AssignedAgentID pgtype.Text `json:"assigned_agent_id"`
	Status          string      `json:"status"`
	BoardPosition   int32       `json:"board_position"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.GoalID,
		arg.Title,
		arg.Description,
		arg.AssignedAgentID,
		arg.Status,
		arg.BoardPosition,
		arg.Metadata,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoalID,
		&i.Title,
		&i.Description,
		&i.AssignedAgentID,
		&i.Status,
		&i.BoardPosition,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
