// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package store

import (
	"context"
	"database/sql"
)

const createDomain = `-- name: CreateDomain :one

INSERT INTO domains (id, slug, name, description, status, metadata)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, slug, name, description, status, metadata, created_at, updated_at
`

type CreateDomainParams struct {
	ID          string         `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Metadata    string         `json:"metadata"`
}

// Work Board CRUD: domains, projects, goals and tasks.
func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (id, project_id, title, description, status, metadata)
VALUES (lower(hex(randomblob(16))), ?, ?, ?, ?, ?)
RETURNING id, project_id, title, description, status, metadata, created_at, updated_at
`

type CreateGoalParams struct {
	ProjectID   string         `json:"project_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Metadata    string         `json:"metadata"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Metadata,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, slug, name, description, domain_id, status, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, name, description, status, owner_agent_id, monthly_budget_usd,
          metadata, domain_id, created_at, updated_at
`

type CreateProjectParams struct {
	ID          string         `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	DomainID    sql.NullString `json:"domain_id"`
	Status      string         `json:"status"`
	Metadata    string         `json:"metadata"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.DomainID,
		arg.Status,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerAgentID,
		&i.MonthlyBudgetUsd,
		&i.Metadata,
		&i.DomainID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, project_id, goal_id, title, description, assigned_agent_id, status,
    board_position, metadata
)
VALUES (lower(hex(randomblob(16))), ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, goal_id, title, description, assigned_agent_id, status,
          board_position, metadata, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID       string         `json:"project_id"`
	GoalID          sql.NullString `json:"goal_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	AssignedAgentID sql.NullString `json:"assigned_agent_id"`
	Status          string         `json:"status"`
	BoardPosition   int64          `json:"board_position"`
	Metadata        string         `json:"metadata"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ProjectID,
		arg.GoalID,
		arg.Title,
		arg.Description,
		arg.AssignedAgentID,
		arg.Status,
		arg.BoardPosition,
		arg.Metadata,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoalID,
		&i.Title,
		&i.Description,
		&i.AssignedAgentID,
		&i.Status,
		&i.BoardPosition,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureInboxProject = `-- name: EnsureInboxProject :one
INSERT INTO projects (id, slug, name, description, status, metadata)
VALUES (
    'inbox',
    'inbox',
    'Inbox',
    'Captura temporal para tareas sin proyecto asignado',
    'active',
    '{"system":true,"purpose":"task_inbox"}'
)
ON CONFLICT (id) DO UPDATE
SET updated_at = projects.updated_at
RETURNING id, slug, name, description, status, owner_agent_id, monthly_budget_usd,
          metadata, domain_id, created_at, updated_at
`

func (q *Queries) EnsureInboxProject(ctx context.Context) (Project, error) {
	row := q.db.QueryRowContext(ctx, ensureInboxProject)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerAgentID,
		&i.MonthlyBudgetUsd,
		&i.Metadata,
		&i.DomainID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one
SELECT id, slug, name, description, status, metadata, created_at, updated_at FROM domains WHERE id = ?
`

func (q *Queries) GetDomain(ctx context.Context, id string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, project_id, title, description, status, metadata, created_at, updated_at FROM goals WHERE id = ?
`

func (q *Queries) GetGoal(ctx context.Context, id string) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoal, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, slug, name, description, status, owner_agent_id, monthly_budget_usd,
       metadata, domain_id, created_at, updated_at FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerAgentID,
		&i.MonthlyBudgetUsd,
		&i.Metadata,
		&i.DomainID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, goal_id, title, description, assigned_agent_id, status,
       board_position, metadata, created_at, updated_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoalID,
		&i.Title,
		&i.Description,
		&i.AssignedAgentID,
		&i.Status,
		&i.BoardPosition,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT id, slug, name, description, status, metadata, created_at, updated_at FROM domains
WHERE status != 'archived'
ORDER BY created_at DESC
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, project_id, title, description, status, metadata, created_at, updated_at FROM goals
ORDER BY project_id, created_at DESC
`

func (q *Queries) ListGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByProject = `-- name: ListGoalsByProject :many
SELECT id, project_id, title, description, status, metadata, created_at, updated_at FROM goals
WHERE project_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListGoalsByProject(ctx context.Context, projectID string) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, description, status, owner_agent_id, monthly_budget_usd,
       metadata, domain_id, created_at, updated_at FROM projects
WHERE status != 'archived'
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.OwnerAgentID,
			&i.MonthlyBudgetUsd,
			&i.Metadata,
			&i.DomainID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, project_id, goal_id, title, description, assigned_agent_id, status,
       board_position, metadata, created_at, updated_at FROM tasks
ORDER BY project_id, status, board_position, created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.GoalID,
			&i.Title,
			&i.Description,
			&i.AssignedAgentID,
			&i.Status,
			&i.BoardPosition,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, goal_id, title, description, assigned_agent_id, status,
       board_position, metadata, created_at, updated_at FROM tasks
WHERE project_id = ?
ORDER BY status, board_position, created_at DESC
`

func (q *Queries) ListTasksByProject(ctx context.Context, projectID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.GoalID,
			&i.Title,
			&i.Description,
			&i.AssignedAgentID,
			&i.Status,
			&i.BoardPosition,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomain = `-- name: UpdateDomain :one
UPDATE domains
SET name = ?, description = ?, status = ?, metadata = ?
WHERE id = ?
RETURNING id, slug, name, description, status, metadata, created_at, updated_at
`

type UpdateDomainParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Metadata    string         `json:"metadata"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, updateDomain,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Metadata,
		arg.ID,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET title = ?, description = ?, status = ?, metadata = ?
WHERE id = ?
RETURNING id, project_id, title, description, status, metadata, created_at, updated_at
`

type UpdateGoalParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Metadata    string         `json:"metadata"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, updateGoal,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Metadata,
		arg.ID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = ?, description = ?, domain_id = ?, status = ?, metadata = ?
WHERE id = ?
RETURNING id, slug, name, description, status, owner_agent_id, monthly_budget_usd,
          metadata, domain_id, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	DomainID    sql.NullString `json:"domain_id"`
	Status      string         `json:"status"`
	Metadata    string         `json:"metadata"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.DomainID,
		arg.Status,
		arg.Metadata,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.OwnerAgentID,
		&i.MonthlyBudgetUsd,
		&i.Metadata,
		&i.DomainID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET project_id = ?, goal_id = ?, title = ?, description = ?, assigned_agent_id = ?,
    status = ?, board_position = ?, metadata = ?
WHERE id = ?
RETURNING id, project_id, goal_id, title, description, assigned_agent_id, status,
          board_position, metadata, created_at, updated_at
`

type UpdateTaskParams struct {
	ProjectID       string         `json:"project_id"`
	GoalID          sql.NullString `json:"goal_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	AssignedAgentID sql.NullString `json:"assigned_agent_id"`
	Status          string         `json:"status"`
	BoardPosition   int64          `json:"board_position"`
	Metadata        string         `json:"metadata"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ProjectID,
		arg.GoalID,
		arg.Title,
		arg.Description,
		arg.AssignedAgentID,
		arg.Status,
		arg.BoardPosition,
		arg.Metadata,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoalID,
		&i.Title,
		&i.Description,
		&i.AssignedAgentID,
		&i.Status,
		&i.BoardPosition,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
